# This code for we check  which stratagy is best for  our dataset:
## mean ,median for numaric
## Most frequent,constant for categorycal

In [93]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import FunctionTransformer

In [94]:
df=pd.read_csv('train.csv')

In [95]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [96]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [118]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [104]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [125]:
# Feature groups
numerical_features = ['Age', 'Fare']
categorical_features = ['Embarked', 'Sex']

# Pipelines
numerical_transform = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transform = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore'))
])

# Preprocessor
preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_transform, numerical_features),
    ('cat', categorical_transform, categorical_features)
])

# Main pipeline
clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Grid Search
param_grid = {
    'preprocessor__num__imputer__strategy': ['mean', 'median'],
    'preprocessor__cat__imputer__strategy': ['most_frequent', 'constant'],
    'classifier__C': [0.1, 1.0, 10, 100]
}

grid_search = GridSearchCV(clf, param_grid, cv=10)
grid_search.fit(x_train, y_train)
print(grid_search.best_params_)

{'classifier__C': 0.1, 'preprocessor__cat__imputer__strategy': 'most_frequent', 'preprocessor__num__imputer__strategy': 'mean'}

###  here shows that  most frequent in catagorical data and mean at mumarical data is best here

In [126]:
print(f"internal cv score:{grid_search.best_score_:.3f}")

internal cv score:0.784

In [128]:
import pandas as pd
cv_result=pd.DataFrame(grid_search.cv_results_);
cv_result

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0        0.023693      0.010347  ...        0.079888                1
1        0.017313      0.001236  ...        0.079888                1
2        0.015564      0.002332  ...        0.079888                1
3        0.015302      0.000377  ...        0.079888                1
4        0.015497      0.001259  ...        0.080160                5
5        0.015050      0.000211  ...        0.080160                5
6        0.015322      0.000203  ...        0.080160                5
7        0.015816      0.000314  ...        0.080160                5
8        0.016372      0.001174  ...        0.080160                5
9        0.017274      0.002141  ...        0.080160                5
10       0.016281      0.000888  ...        0.080160                5
11       0.017153      0.002290  ...        0.080160                5
12       0.016239      0.002133  ...        0.080160                5
13       0.015245      0.000485  ...        0.080160                5
14       0.015936      0.000245  ...        0.080160                5
15       0.016308      0.000323  ...        0.080160                5

[16 rows x 21 columns]