## KNN imputer  ( That means  A null value set by )

In [16]:
import pandas as  pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.linear_model import LogisticRegression

In [17]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [18]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [19]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [20]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
# KNN imputer:
knn=KNNImputer(weights='distance')
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test);

In [31]:
ddf=pd.DataFrame(x_train_trf,columns=x_train.columns)

In [32]:
ddf

     Pclass        Age      Fare
0       1.0  45.500000   28.5000
1       2.0  23.000000   13.0000
2       3.0  32.000000    7.9250
3       3.0  26.000000    7.8542
4       3.0   6.000000   31.2750
..      ...        ...       ...
707     3.0  21.000000    7.6500
708     1.0  40.111111   31.0000
709     3.0  41.000000   14.1083
710     1.0  14.000000  120.0000
711     1.0  21.000000   77.2875

[712 rows x 3 columns]

In [33]:
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [34]:
ddf.isnull().mean()*100

Pclass    0.0
Age       0.0
Fare      0.0
dtype: float64

In [35]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [36]:
clf=LogisticRegression();
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)
accuracy_score(y_pred,y_test)

0.7374301675977654